name: deploy-php

on:
  push:
    branches:
      - main
    paths:
      - "**"
  workflow_dispatch:

env:
  # AWSリージョン
  REGION: "ap-northeast-1"

  # ECR設定
  ECR_REPO_PHP: "ecr-php-yoshiike-0310"
  ECR_REPO_PHP_Apache: "ecr-php-apache-yoshiike-0310"

  CONTAINER_NAME: "php"

  # ECS Task設定
  TASK_FAMILY: "task-php-yoshiike-0310"
  CONTAINER_PORT: "80"
  TASK_ROLE: "TaskExecutionRole-yoshiike-0310"

  # RDSのエンドポイント
  RDS_ENDPOINT: "db-yoshiike-0310.cnabwrjqs09i.ap-northeast-1.rds.amazonaws.com"

  # CodeDeploy設定
  CODEDEPLOY_APP: "php-codedeploy-app-yoshiike-0310"
  CODEDEPLOY_GROUP: "php-codedeploy-group-yoshiike-0310"

  # IAMロールのARN（CloudFormationで作成したもの）
  AWS_ROLE_ARN: "arn:aws:iam::527151769671:role/GitHubActionsRole-yoshiike-0310"

jobs:

  deploy:

    runs-on: ubuntu-latest
    # 【必須】OIDC認証のための権限設定
    permissions:
      id-token: write
      contents: read

    steps:

    # --------------------------------------------------
    # ソースコード取得
    # --------------------------------------------------
    - name: Checkout repository
      uses: actions/checkout@v4

    # --------------------------------------------------
    # AWS認証 (OIDC方式)
    # --------------------------------------------------
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.REGION }}
        role-to-assume: ${{ env.AWS_ROLE_ARN }}

    # --------------------------------------------------
    # AWSアカウントIDの取得と登録
    # 以降のステップで $ACCOUNT_ID として使い回せます
    # --------------------------------------------------
    - name: Set AWS Account ID
      run: |
        ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
        echo "ACCOUNT_ID=${ACCOUNT_ID}" >> $GITHUB_ENV        

    # --------------------------------------------------
    # ECRログイン
    # --------------------------------------------------
    - name: Login to Amazon ECR
      run: |
        echo "Logging in to Amazon ECR..."

        aws ecr get-login-password --region ${REGION} | \
        docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com

        echo "ECR login successful."

    # --------------------------------------------------
    # Dockerイメージビルド
    # --------------------------------------------------
    #docker build --build-arg ACCOUNT_ID=${ACCOUNT_ID} --build-arg REGION=${REGION} --build-arg ECR_REPO_PHP_Apache=${ECR_REPO_PHP_Apache} -t ${ECR_REPO_PHP}:latest ./app

    - name: Build Docker image
      run: |
        echo "Building Docker image..."

        docker build \
          --build-arg ACCOUNT_ID=${ACCOUNT_ID} \
          --build-arg REGION=${REGION} \
          --build-arg ECR_REPO_PHP_Apache=${ECR_REPO_PHP_Apache} \
          -t ${ECR_REPO_PHP}:latest \
          ./app

        echo "Docker image build completed."

    # --------------------------------------------------
    # Dockerイメージタグ付け
    # --------------------------------------------------
    - name: Tag Docker image
      run: |
        echo "Tagging Docker image for ECR..."

        docker tag ${ECR_REPO_PHP}:latest ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$ECR_REPO_PHP:latest

    # --------------------------------------------------
    # ECRへPush
    # --------------------------------------------------
    - name: Push image to ECR
      run: |
        echo "Pushing Docker image to ECR..."

        docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/$ECR_REPO_PHP:latest

        echo "Image push completed."

    # --------------------------------------------------
    # TaskDefinition生成
    # --------------------------------------------------
    - name: Generate Task Definition
      run: |
        echo "Generating ECS Task Definition..."

        cat <<EOF > taskdef.json
        {
          "family": "${TASK_FAMILY}",
          "networkMode": "awsvpc",
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "512",
          "memory": "1024",
          "executionRoleArn": "arn:aws:iam::${ACCOUNT_ID}:role/${TASK_ROLE}",
          "containerDefinitions": [
            {
              "name": "${CONTAINER_NAME}",
              "image": "${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_REPO_PHP}:latest",
              "portMappings": [
                {
                  "containerPort": ${CONTAINER_PORT},
                  "protocol": "tcp"
                }
              ],
              "essential": true,
              "environment": [
                { "name": "DB_HOST", "value": "${RDS_ENDPOINT}" },
                { "name": "DB_USER", "value": "root" },
                { "name": "DB_PASS", "value": "root1234" },
                { "name": "DB_NAME", "value": "sampledb" }
              ]
            }
          ]
        }
        EOF

        echo "Task Definition file created."


    #以下、実務では、①TaskDefinitionのARNの取得、②appspec.yml準備、③TaskDefinition ARNをappspecに反映の順番で
    #ステップを分けた方がログが管理しやすくなり好ましい
    # --------------------------------------------------
    # appspec.yml準備
    # --------------------------------------------------
    - name: Prepare appspec.yml
      run: |
        echo "Preparing CodeDeploy AppSpec file..."

        ls -l CodeDeploy/
        pwd
        cp ./CodeDeploy/appspec.yml .
        echo "Generated files:"
        ls -l
    # --------------------------------------------------
    # TaskDefinitionのARNの取得とappspecへの反映
    # --------------------------------------------------
    - name: Getting Task Definition ARN and Updating AppSpec with TaskDefinition
      run: |
        echo " Getting Task Definition ARN..."

        TASK_DEF_ARN=$(aws ecs register-task-definition \
          --cli-input-json file://taskdef.json \
          --query taskDefinition.taskDefinitionArn \
          --output text)

        echo ${TASK_DEF_ARN}
        echo "TASK_DEF_ARN=${TASK_DEF_ARN}" >> $GITHUB_ENV
    # --------------------------------------------------
    # TaskDefinition ARNをappspecに反映
    # --------------------------------------------------
    - name: Update AppSpec with TaskDefinition
      run: |
        echo "Updating Task Definition in AppSpec..."

        sed -i "s|<TASK_DEFINITION>|$TASK_DEF_ARN|g" appspec.yml

    # --------------------------------------------------
    # CodeDeployデプロイ開始
    # --------------------------------------------------
    - name: Start CodeDeploy deployment
      run: |
        echo "Starting CodeDeploy deployment..."
        
        # 1. jq を使って appspec.yml の中身を JSON 文字列として整形し、変数に格納
        APPSPEC_JSON=$(cat appspec.yml | jq -Rs .)

        # 2. 変数を使ってデプロイコマンドを実行
        # --revision の全体をシングルクォートで囲み、変数を展開します
        DEPLOY_ID=$(aws deploy create-deployment \
          --application-name $CODEDEPLOY_APP \
          --deployment-group-name $CODEDEPLOY_GROUP \
          --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
          --revision revisionType=AppSpecContent,appSpecContent='{"content":'$APPSPEC_JSON'}' \
          --region ${REGION} \
          --query deploymentId \
          --output text)

        echo "DEPLOY_ID=$DEPLOY_ID" >> $GITHUB_ENV
        echo "Deployment ID: $DEPLOY_ID"

    # --------------------------------------------------
    # デプロイ完了待機
    # --------------------------------------------------
    - name: Wait for deployment to complete
      run: |
        echo "Waiting for CodeDeploy deployment to finish..."

        aws deploy wait deployment-successful \
          --deployment-id $DEPLOY_ID

        echo "Deployment completed successfully!"